-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS OpettajanInstrumentti CASCADE;
DROP TABLE IF EXISTS Instrumentti CASCADE;
DROP TABLE IF EXISTS OppilaanInstrumentti CASCADE;
DROP TABLE IF EXISTS Opettaja CASCADE;
DROP TABLE IF EXISTS OpettajanOppilas CASCADE;
DROP TABLE IF EXISTS Oppilas CASCADE;
DROP TABLE IF EXISTS OpettajanMateriaali CASCADE;
DROP TABLE IF EXISTS Materiaali CASCADE;
DROP TABLE IF EXISTS SoittotunninMateriaali CASCADE;
DROP TABLE IF EXISTS Soittotunti CASCADE;